sudo: required
services:
  - docker

before_install:
  - docker build -t gabiswas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gabiswas/react-test npm test

language: generic

after_success:
  - docker build -t gabiswas/multi-client ./client
  - docker build -t gabiswas/multi-nginx ./nginx
  - docker build -t gabiswas/multi-server ./server
  - docker build -t gabiswas/multi-worker ./worker
  # Login to Docker Cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push to docker hub
  - docker push gabiswas/multi-client
  - docker push gabiswas/multi-nginx
  - docker push gabiswas/multi-server
  - docker push gabiswas/multi-worker


  # Deploy Script
deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-511976750636'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
